language: rust
rust:
  - stable
before_install:
  - deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main
  - deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main
addons:
  apt:
    update: true
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required