language: rust
rust:
  - stable
compiler:
  - clang
before_install: 
  - apt install -y llvm 
  - llc -version
os: linux
dist: trusty
sudo: required
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-precise
    packages:
      - clang-6.0