language: rust
rust:
  - stable
before_install:
  - sudo sh -c "echo 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main' >> /etc/apt/sources.list"
  - sudo apt-get update
  - sudo apt-install llvm
addons:
  apt:
    update: true
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required