language: rust
rust:
  - stable
os: linux
dist: trusty
sudo: required
env:
  global:
    - GCC=gcc-5
    - GXX=g++-5
before_install: 
  - export CC=/usr/bin/$GCC
  - export CXX=/usr/bin/$GXX
  - llc -version

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - gcc-5
      - g++-5
      - libgmp-dev
      - llvm-6.0-dev
      - libllvm-6.0
      - llvm-6.0
      - llvm-6.0-runtime