language: rust
rust:
  - stable
    
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          update: true
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'