language: rust
rust:
  - stable
before_install:
  - sudo sh -c "echo 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main' >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
  - sudo apt-get update
  - sudo apt install llvm
addons:
  apt:
    update: true
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required