language: rust
rust:
  - stable
before_install:
  - git clone https://github.com/llvm-mirror/llvm.git
  - cmake -DCMAKE_BUILD_TYPE=Release llvm 
  - cmake --build /home/travis/build/elipmoc/Ruscall
addons:
  apt:
    update: true
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake